#
#  Makefile for the kernel Sensor device drivers.
#

obj-$(CONFIG_SENSORS_CORE)		+= sensors_core.o
obj-$(CONFIG_SENSORS_ALPS)		+= alps-input.o
obj-$(CONFIG_SENSORS_HSCD) 			+= hscd_i2c.o
obj-$(CONFIG_SENSORS_BMA222)		+= bma222.o
obj-$(CONFIG_SENSORS_BMA222E)		+= bma222e.o
obj-$(CONFIG_USE_BMA_INITLIB)	+= bmainit.o
obj-$(CONFIG_PROXIMITY_SENSOR)	+= gp2a.o

